[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tibetan-wer"
dynamic = ["version"]
authors = [
  { name="billingsmoore", email="billingsmoore@gmail.com" },
]
description = "Character, syllable, and segmented word error rates for Tibetan text."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic",
]
dependencies = [
  "botok",
  "numpy"
]

[project.optional-dependencies]
bert = ["transformers", "torch"]
gemini = ["google-genai"]
fast = ["rapidfuzz"]
dev = ["pytest", "rapidfuzz", "jiwer"]

[project.scripts]
tibetan-wer = "tibetan_wer.cli:main"

[project.urls]
Homepage = "https://github.com/billingsmoore/tibetan-wer"
Issues = "https://github.com/billingsmoore/tibetan-wer/issues"

[tool.hatch.version]
path = "src/tibetan_wer/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/tibetan_wer"]
